//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHomeEnergySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChartTable
    {
        public string Date { get; set; }
        public Nullable<double> SolarPanel { get; set; }
        public Nullable<double> BaterryProduction { get; set; }
        public Nullable<double> BatteryConsumption { get; set; }
        public Nullable<double> ExchangePositive { get; set; }
        public Nullable<double> ExchangeNegative { get; set; }
        public Nullable<double> Consumer { get; set; }
        public double Price { get; set; }
    }
}
