//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHomeEnergySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumerTable
    {
        public string Name { get; set; }
        public Nullable<double> Consumption { get; set; }
        public string State { get; set; }
    }
}
